"""Funciones mutadoras para el patrón Prototype

Este módulo contiene funciones reutilizables que modifican recursos Terraform clonados.
Las funciones mutadoras operan in-place sobre el diccionario que reciben.
"""

from typing import Dict, Any

def convert_null_to_local_file(resource_dict: Dict[str, Any],
                                filename: str = "output.txt",
                                content: str = "Generated by IaC") -> None:
    """
    Convierte un recurso null_resource a local_file.

    Esta función mutadora extrae los triggers del null_resource y los convierte
    en un recurso local_file con nombre de archivo y contenido personalizables.

    Args:
        resource_dict: Diccionario del recurso a mutar (debe contener null_resource).
        filename: Nombre del archivo local a crear.
        content: Contenido del archivo.

    Ejemplo:
        >>> from iac_patterns.factory import NullResourceFactory
        >>> from iac_patterns.prototype import ResourcePrototype
        >>> base = NullResourceFactory.create("app")
        >>> proto = ResourcePrototype(base)
        >>> clone = proto.clone(lambda d: convert_null_to_local_file(d, "app.txt", "Hello"))
        >>> # El clone ahora contiene local_file en lugar de null_resource
    """
    if "resource" not in resource_dict:
        raise ValueError("resource_dict debe contener clave 'resource'")

    resources = resource_dict["resource"]
    if not resources or not isinstance(resources, list):
        raise ValueError("'resource' debe ser una lista no vacía")

    # Buscar null_resource en la estructura
    for resource_block in resources:
        if "null_resource" in resource_block:
            # Extraer triggers del null_resource original
            null_res = resource_block["null_resource"][0]
            original_name = list(null_res.keys())[0]
            triggers = null_res[original_name][0].get("triggers", {})

            # Crear nuevo recurso local_file
            new_name = f"{original_name}_file"
            local_file_resource = {
                new_name: [{
                    "filename": filename,
                    "content": content,
                    # Preservar triggers originales como comentario en el contenido
                    "file_permission": "0644"
                }]
            }

            # Reemplazar null_resource con local_file
            del resource_block["null_resource"]
            resource_block["local_file"] = [local_file_resource]

            break

def rename_resource(resource_dict: Dict[str, Any],
                   old_name: str,
                   new_name: str) -> None:
    """
    Renombra un recurso manteniendo su tipo.

    Args:
        resource_dict: Diccionario del recurso.
        old_name: Nombre actual del recurso.
        new_name: Nuevo nombre para el recurso.

    Ejemplo:
        >>> clone = proto.clone(lambda d: rename_resource(d, "app", "web_server"))
    """
    if "resource" not in resource_dict:
        return

    for resource_block in resource_dict["resource"]:
        for resource_type, resources_list in resource_block.items():
            if not resources_list:
                continue
            resources = resources_list[0]
            if old_name in resources:
                resources[new_name] = resources.pop(old_name)
                break

def add_trigger(resource_dict: Dict[str, Any],
               trigger_key: str,
               trigger_value: Any) -> None:
    """
    Agrega un nuevo trigger a un recurso null_resource.

    Args:
        resource_dict: Diccionario del recurso.
        trigger_key: Nombre del trigger a agregar.
        trigger_value: Valor del trigger.

    Ejemplo:
        >>> clone = proto.clone(lambda d: add_trigger(d, "region", "us-east-1"))
    """
    if "resource" not in resource_dict:
        return

    for resource_block in resource_dict["resource"]:
        if "null_resource" in resource_block:
            null_res = resource_block["null_resource"][0]
            for resource_name, config_list in null_res.items():
                if config_list and "triggers" in config_list[0]:
                    config_list[0]["triggers"][trigger_key] = trigger_value
                    break
